version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  server:
    build: ./api/
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: numer
      DB_PORT: 3307

  app:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - server